name: Lint PR title
description: Run linter on the PR title

inputs:
  command:
    description: Lint command to run
    default: 'npm run lint:commit'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 16.7.0
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Lint title
      run: echo -n "${{ github.event.pull_request.title }}" | ${{ inputs.command }}
      shell: bash
