name: Update Node.js versions
description: Update Node.js versions in all files

outputs:
  version:
    description: The new version of Node.js
    value: ${{ steps.update-node-versions.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get relative path to composite action
      uses: actions/github-script@v6.0.0
      id: get-relative-action-path
      with:
        script: return require('path').relative('${{ github.workspace }}', '${{ github.action_path }}');
        result-encoding: string
    - name: Setup Node.js for composite action
      uses: actions/setup-node@v2.5.1
      with:
        node-version-file: ${{ steps.get-relative-action-path.outputs.result }}/../.nvmrc
    - name: Install dependencies of composite action
      run: cd ${{ github.action_path }}/../ && npm ci
      shell: bash
    - name: Update Node.js versions
      id: update-node-versions
      run: cd ${{ github.action_path }}/../ && npm run node-versions-update "${{ github.workspace }}"
      shell: bash
    - name: Setup new Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ steps.update-node-versions.outputs.version }}
        cache: npm
    - name: Update the lock file
      run: npm i
      shell: bash
