name: Install
description: Checkout and install dependencies

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1'
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
  node-version-file:
    description: 'File containing the version Spec of the version to use. Default: .nvmrc'
    default: .nvmrc

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Check lock file version
      run: >-
        grep '"lockfileVersion": 2' package-lock.json
      shell: bash
    - name: Setup Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
