name: CI status

on:
  workflow_run:
    workflows: CI
    types: completed
    branches: [main, latest]
  workflow_call:
    secrets:
      token:
        description: GitHub access token
      app-id:
        description: GitHub app ID
      private-key:
        description: GitHub app private key

jobs:
  send-status:
    name: Send CI status
    runs-on: ubuntu-latest
    concurrency:
      group: ci-status-${{ github.event.workflow_run.head_sha }}
      cancel-in-progress: true
    env:
      CI_STATE: pending
      CI_DESCRIPTION: Waiting
      CLUENAR_ACTIONS_VERSION: v1.0.0
      SECRET_TOKEN: ${{ secrets.token }}
      SECRET_APP_ID: ${{ secrets.app-id || secrets.CLUENAR_PUBLIC_BOT_APP_ID }}
      SECRET_PRIVATE_KEY: ${{ secrets.private-key || secrets.CLUENAR_PUBLIC_BOT_PRIVATE_KEY }}

    steps:
      - name: Check required secrets
        if: env.SECRET_TOKEN == null && (env.SECRET_APP_ID == null || env.SECRET_PRIVATE_KEY == null)
        run: exit 1
        shell: bash

      - name: Set cluenar/actions version
        if: github.event_name != 'workflow_call'
        run: echo "CLUENAR_ACTIONS_VERSION=main" >> $GITHUB_ENV

      - name: Get bot token
        id: get-bot-token
        if: env.SECRET_TOKEN == null
        uses: cluenar/actions/get-github-app-token@${{ env.CLUENAR_ACTIONS_VERSION }}
        with:
          app-id: ${{ env.SECRET_APP_ID }}
          private-key: ${{ env.SECRET_PRIVATE_KEY }}

      - name: Set initial state
        if: github.event.action == 'requested'
        run: |
          echo "CI_STATE=pending" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=In progress" >> $GITHUB_ENV

      - name: Set success state
        if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'success'
        run: |
          echo "CI_STATE=success" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=Passed" >> $GITHUB_ENV

      - name: Set failure state
        if: github.event.action == 'completed' && github.event.workflow_run.conclusion == 'failure'
        run: |
          echo "CI_STATE=failure" >> $GITHUB_ENV &&
          echo "CI_DESCRIPTION=Failed" >> $GITHUB_ENV

      - name: Send status
        uses: octokit/request-action@v2.1.9
        with:
          route: POST /repos/{owner}/{repo}/statuses/{sha}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Status / CI
          state: ${{ env.CI_STATE }}
          description: ${{ env.CI_DESCRIPTION }}
          target_url: ${{ github.event.workflow_run.html_url }}
          GITHUB_TOKEN: ${{ env.SECRET_TOKEN || steps.get-bot-token.outputs.token }}
