name: CI

on: push

concurrency: ci-${{ github.sha }}

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.0

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.0
      - name: Lint files
        run: npm run lint all
        env:
          CI: true
