name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_call:
    inputs:
      command:
        type: string
        description: Lint command to run
        default: 'npm run lint:commit'

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    env:
      INPUT_COMMAND: ${{ inputs.command || 'npm run lint commit' }}

    steps:
      - name: Install (main)
        if: github.event_name != 'workflow_call'
        uses: cluenar/actions/install@main

      - name: Install (version)
        if: github.event_name == 'workflow_call'
        uses: cluenar/actions/install@v1.0.0

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ env.INPUT_COMMAND }}
