name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_call:
    inputs:
      command:
        type: string
        description: Lint command to run
        default: 'npm run lint:commit'

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    env:
      CLUENAR_ACTIONS_VERSION: v1.0.0
      INPUT_COMMAND: ${{ inputs.command || 'npm run lint commit' }}

    steps:
      - name: Set cluenar/actions version
        if: github.event_name != 'workflow_call'
        run: echo "CLUENAR_ACTIONS_VERSION=main" >> $GITHUB_ENV

      - name: Install
        uses: cluenar/actions/install@${{ env.CLUENAR_ACTIONS_VERSION }}

      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | ${{ env.INPUT_COMMAND }}
