name: Update lock file

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (npm or yarn)
        default: npm
      node-version:
        type: string
        description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
      node-version-file:
        type: string
        description: 'File containing the version Spec of the version to use. Default: .nvmrc'
        default: .nvmrc
    secrets:
      token:
        description: GitHub access token
      appId:
        description: GitHub app ID
      privateKey:
        description: GitHub app private key

jobs:
  update-lock-file:
    name: Update lock file
    runs-on: ubuntu-latest
    env:
      SECRETS_TOKEN: ${{ secrets.token }}
      SECRETS_APP_ID: ${{ secrets.appId }}
      SECRETS_PRIVATE_KEY: ${{ secrets.privateKey }}

    steps:
      - name: Check required secrets
        if: env.SECRETS_TOKEN == null && (env.SECRETS_APP_ID == null || env.SECRETS_PRIVATE_KEY == null)
        run: exit 1
        shell: bash

      - name: Get bot token
        id: get-bot-token
        if: env.SECRETS_TOKEN == null
        uses: cluenar/actions/get-github-app-token@main
        with:
          appId: ${{ secrets.appId }}
          privateKey: ${{ secrets.privateKey }}

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: ${{ inputs.manager }}
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - name: Update the NPM lock file
        if: inputs.manager == 'npm'
        run: rm package-lock.json && npm i

      - name: Update the Yarn lock file
        if: inputs.manager == 'yarn'
        run: rm yarn.lock && yarn

      - name: Create a pull request with the updated file
        uses: branoholy/update-files-action@main
        with:
          token: ${{ secrets.token || steps.get-bot-token.outputs.token }}
          branch.name: deps-update-lock-file
          branch.recreate: true
          commit.paths: package-lock.json
          commit.message: 'deps(lock): Update lock file'
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of dependencies in `package-lock.json`.
          pull-request.labels: |
            type: deps
            scope: lock
