name: Update Node.js

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (npm or yarn)
        default: npm
      node-version:
        type: string
        description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
      node-version-file:
        type: string
        description: 'File containing the version Spec of the version to use. Default: .nvmrc'
        default: .nvmrc
    secrets:
      token:
        description: GitHub access token
      app-id:
        description: GitHub app ID
      private-key:
        description: GitHub app private key

jobs:
  update-node:
    name: Update Node.js
    runs-on: ubuntu-latest
    env:
      SECRETS_TOKEN: ${{ secrets.token }}
      SECRETS_APP_ID: ${{ secrets.app-id }}
      SECRETS_PRIVATE_KEY: ${{ secrets.private-key }}

    steps:
      - name: Check required secrets
        if: env.SECRETS_TOKEN == null && (env.SECRETS_APP_ID == null || env.SECRETS_PRIVATE_KEY == null)
        run: exit 1
        shell: bash

      - name: Get bot token
        id: get-bot-token
        if: env.SECRETS_TOKEN == null
        uses: cluenar/actions/get-github-app-token@main
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.private-key }}

      - name: Install
        uses: cluenar/actions/install@main
        with:
          manager: ${{ inputs.manager }}
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - name: Update Node.js versions
        id: update-node-versions
        run: npm run node-versions-update

      - name: Setup new Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: ${{ inputs.manager }}
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - name: Update the NPM lock file
        if: inputs.manager == 'npm'
        run: npm i

      - name: Update the Yarn lock file
        if: inputs.manager == 'yarn'
        run: yarn

      - name: Create a pull request with the updated files
        uses: branoholy/update-files-action@main
        with:
          token: ${{ secrets.token || steps.get-bot-token.outputs.token }}
          branch.name: deps-update-node
          branch.recreate: true
          commit.paths: |
            .nvmrc
            package.json
            package-lock.json
            .github/workflows/*.yaml
          commit.message: 'deps(dev): Update Node.js to ${{ steps.update-node-versions.outputs.version }}'
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of Node.js to version ${{ steps.update-node-versions.outputs.version }}.
          pull-request.labels: |
            type: deps
            scope: dev
