name: Update Node.js

on:
  schedule:
    - cron: '0 13 * * 0'
  workflow_dispatch:
  workflow_call:
    inputs:
      manager:
        type: string
        description: Package manager (npm or yarn)
        default: npm
      node-version:
        type: string
        description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
      node-version-file:
        type: string
        description: 'File containing the version Spec of the version to use. Default: .nvmrc'
        default: .nvmrc
    secrets:
      token:
        description: GitHub access token
      app-id:
        description: GitHub app ID
      private-key:
        description: GitHub app private key

jobs:
  update-node:
    name: Update Node.js
    runs-on: ubuntu-latest
    env:
      INPUT_MANAGER: ${{ inputs.manager || 'npm' }}
      INPUT_NODE_VERSION: ${{ inputs.node-version }}
      INPUT_NODE_VERSION_FILE: ${{ inputs.node-version-file || '.nvmrc' }}
      SECRET_TOKEN: ${{ secrets.token }}
      SECRET_APP_ID: ${{ secrets.app-id || secrets.CLUENAR_PUBLIC_BOT_APP_ID }}
      SECRET_PRIVATE_KEY: ${{ secrets.private-key || secrets.CLUENAR_PUBLIC_BOT_PRIVATE_KEY }}

    steps:
      - name: Check required secrets
        if: env.SECRET_TOKEN == null && (env.SECRET_APP_ID == null || env.SECRET_PRIVATE_KEY == null)
        run: exit 1
        shell: bash

      - name: Get bot token
        id: get-bot-token
        if: env.SECRET_TOKEN == null
        uses: cluenar/actions/get-github-app-token@main
        with:
          app-id: ${{ env.SECRET_APP_ID }}
          private-key: ${{ env.SECRET_PRIVATE_KEY }}

      - name: Install
        uses: cluenar/actions/install@main
        with:
          manager: ${{ env.INPUT_MANAGER }}
          node-version: ${{ env.INPUT_NODE_VERSION }}
          node-version-file: ${{ env.INPUT_NODE_VERSION_FILE }}

      - name: Update Node.js versions
        id: update-node-versions
        run: npm run node-versions-update

      - name: Setup new Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: ${{ env.INPUT_MANAGER }}
          node-version: ${{ env.INPUT_NODE_VERSION }}
          node-version-file: ${{ env.INPUT_NODE_VERSION_FILE }}

      - name: Update the NPM lock file
        if: env.INPUT_MANAGER == 'npm'
        run: npm i

      - name: Update the Yarn lock file
        if: env.INPUT_MANAGER == 'yarn'
        run: yarn

      - name: Create a pull request with the updated files
        uses: branoholy/update-files-action@main
        with:
          token: ${{ env.SECRET_TOKEN || steps.get-bot-token.outputs.token }}
          branch.name: deps-update-node
          branch.recreate: true
          commit.paths: |
            .nvmrc
            package.json
            package-lock.json
            .github/workflows/*.yaml
          commit.message: 'deps(dev): Update Node.js to ${{ steps.update-node-versions.outputs.version }}'
          commit.token: ${{ steps.get-bot-token.outputs.token || secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of Node.js to version ${{ steps.update-node-versions.outputs.version }}.
          pull-request.labels: |
            type: deps
            scope: dev
